// build.gradle

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'java-library-distribution'
apply plugin: 'idea'
apply plugin: 'application'
apply plugin: 'maven-publish'

repositories {
    mavenLocal()
    maven {
        url 'http://maven.aliyun.com/nexus/content/groups/public/'
        allowInsecureProtocol = true
    }
    maven {
        url "http://maven.springframework.org/release"
        allowInsecureProtocol = true
    }
    maven {
        url "http://maven.restlet.org"
        allowInsecureProtocol = true
    }
    mavenCentral()
}

// 配置发布信息
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'com.sp'       // 修改为你的 groupId
            artifactId = 'smartPutty'     // 修改为你的 artifactId
            version = '1.0.0'             // 修改为你的版本号
        }
    }
}

dependencies {
    implementation fileTree(dir: 'lib', include: '*.jar')
    implementation fileTree(dir: 'libArch', include: 'swt.x64_3.105.3.v20170228-0512.jar')
    implementation group: 'org.springframework', name: 'spring-core', version: '4.3.29.RELEASE'
    implementation group: 'commons-io', name: 'commons-io', version: '2.5'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.4'
    implementation group: 'commons-net', name: 'commons-net', version: '3.5'
    implementation group: 'com.h2database', name: 'h2', version: '1.4.200'
//    implementation group: 'log4j', name: 'log4j', version: '1.2.17'
    implementation group: 'ch.qos.logback', name: 'logback-core', version: '1.2.3'
    implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'
    implementation group: 'commons-codec', name: 'commons-codec', version: '1.9'
    implementation group: 'org.hibernate', name: 'hibernate-core', version: '5.4.22.Final'
    implementation group: 'org.projectlombok', name: 'lombok', version: '1.16.10'
}


distTar.enabled = false
//distZip.shouldRunAfter('copyImage')

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
}

task compile(type: JavaCompile) {
    source = fileTree(dir: 'src', includes: ['**/*.java', '*.properties'])
    destinationDir = file('build/classes/main')
}


distributions {
    main {
        contents {
            into('icon') {
                from 'icon'
            }

            from 'VERSION'
            into('config') { from 'config' }
            into('database') { from 'database' }
            into('app') { from 'src/main/resources/app' }
            into('doc') { from 'doc' }
        }
    }
}
distZip {
    archiveName "SmartPutty-x64.zip"
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.sp.ui.MainFrame',
        )
    }
    from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
    baseName 'SmartPutty'
}


mainClassName = 'com.sp.UI.MainFrame'
