# 标题
title = 汗牛追风小助手

# 版本
version = 1.0.0

#
keyGenerator = app\\putty\\puttygen.exe

#
plink = app\\putty\\plink.exe

#
putty = app\\putty\\putty.exe

#
waitForInitTime = 200

#
windowPositionSize = 100,100,1200,900

#
showWelcomePage = false

#
viewConnectionBar = true

#
viewBottomQuickBar = true

#
viewAppBar = true

#
dictionaryUrl = http://dict.youdao.com/w/eng/

#
windowsBaseDrive = C:

#
username = zippoy

#
pin =

#
otp =

#
passphrase =
